/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HomePageLinks: typeof import('./components/HomePageLinks.vue')['default']
    HomePageRotatingText: typeof import('./components/HomePageRotatingText.vue')['default']
    HomePageTitle: typeof import('./components/HomePageTitle.vue')['default']
    LangSwitch: typeof import('./components/LangSwitch.vue')['default']
    MainLogo: typeof import('./components/icons/MainLogo.vue')['default']
    MenuButton: typeof import('./components/icons/MenuButton.vue')['default']
    RotatingText: typeof import('./components/RotatingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
